### ISSUE TITLE
Website Missing Webring

### ISSUE THREAD

**Issue by alialiwa2005** [hackclub/webring#34]
Hello. I've recently noticed that this website: https://fayd.me/ does not have Hack Club webring embedded, and I can't proceed to the next hack clubber website because of this. Kindly fix this. Thanks!

**Comment by sampoder** [comment]
Fixed in #31

**Comment by googol88** [comment]
@faisalsayed10 you have been temporarily removed from the webring since we can't find your embed :(
You can still add it back and I'd be more than happy to accept your PR afterwards.
